academy/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home_view,name='home'),
    path('register/',views.register_view,name='register'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('courses/',views.courses_view,name='courses'),
    path('course/<int:id>',views.coursedetails_view,name='coursedetails'),
    path('addcourse/',views.addcourse_view,name='addcourse'),
    path('updatecourse/<int:id>',views.updatecourse_view,name='updatecourse'),
    path('deletecourse/<int:id>',views.deletecourse_view,name='deletecourse'),
    path('trainers/',views.trainers_view,name='trainers'),
    path('trainer/<int:id>',views.trainerdetailes_view,name='trainerdetails'),
    path('addtrainer/',views.addtrainer_view,name='addtrainer'),
    path('updatetrainer/<int:id>',views.updatetrainer_view,name='updatetrainer'),
    path('dalatetrainer/<int:id>',views.deletetrainer_view,name='deletetrainer'),
    path('students/',views.students_view,name='students'),
    path('student/<int:id>',views.studentdetails_view,name='studentdetails'),
    path('addstudent/',views.addstudent_view,name='addstudent'),
    path('updatestudent/<int:id>',views.updatestudent_view,name='updatestudent'),
    path('deletestudent/<int:id>',views.deletestudent_view,name='deletestudent'),

]

training_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('academy/',include('academy.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

academy/models.py
from django.db import models

# Create your models here.
class CourseModel(models.Model):
    course_name = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    duration = models.CharField(max_length=50)
    course_image = models.ImageField(upload_to='courses/', blank=True, null=True)

    def __str__(self):
        return self.course_name

class TrainerModel(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.EmailField(unique=True)
    expertise = models.CharField(max_length=20)
    trainer_photo = models.ImageField(upload_to='trainers/', default='default.jpg')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

class StudentModel(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    enrolled_course = models.ForeignKey(CourseModel,on_delete=models.SET_NULL,blank=True,null=True)
    trainer = models.ForeignKey(TrainerModel,on_delete=models.SET_NULL,blank=True,null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
    def full_name(self):
        return f'{self.first_name} {self.last_name}'
    

templates/addcourse.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
    <h1 style="text-align: center;">Add Course Page</h1>
    <br>
    <form action="{% url 'addcourse' %}" method="post" enctype="multipart/form-data" style="width: 500px;text-align:left;margin: auto;">
        {% csrf_token %}
        {{form | crispy}}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/addstudent.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
    <h1 style="text-align: center;">Add Student Page</h1>
    <br>
    <form action="{% url 'addstudent' %}" method="post" style="width: 500px;text-align: left;margin: auto;">
        {% csrf_token %}
        {{form | crispy}}
        <button type="submit" >Submit</button>
    </form>
</body>
</html>

templates/addtrainer.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
    <h1 style="text-align: center;">Add Trainer Page</h1>
    <br>
    <form action="{% url 'addtrainer' %}" method="post" enctype="multipart/form-data" style="width: 500px;text-align:left;margin: auto;">
        {% csrf_token %}
        {{form | crispy}}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/coursedetails.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
  <body>
    <center>
    <h1>Course Detail Page - {{course.course_name}}</h1>
    <br>
    <img src="{{course.course_image.url}}" alt="{{course.course_name}} Image" style="width: 200px;height: 200px;">
    <p>Name:{{course.course_name}}</p>
    <p>Discription:{{course.description}}</p>
    <p>Duration:{{course.duration}}</p>
    </center>
  </body>
</html>

templates/courses.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Courses</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <center>
        <ul style="list-style: none; ">
            <li>
                <a href="{% url 'home' %}">Back to Home</a>
            </li>
            {% if perms.academy.add_coursemodel %}
            <li style="margin-top: 10px;">
                <a href="{% url 'addcourse' %}">Add Course</a>
            </li>
            {% endif %}
        </ul>
        <h1>Total Available Courses</h1>
        <br>
        <table border="1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>COURSE NAME</th>
                    <th>IMAGE</th>
                    <th>DESCRIPTION</th>
                    <th>DURATION</th>
                    <th>ACTION</th>
                </tr>
            </thead>

            <tbody>
                {% for course in courses%}
                <tr>
                    <td>{{course.id}}</td>
                    <td>{{course.course_name}}</td>
                    <td><img src="{{course.course_image.url}}" style="width: 80px;height: 80px;"></td>
                    <td>{{course.description}}</td>
                    <td>{{course.duration}}</td>
                    <td>
                        <div>
                            <a href="{% url 'coursedetails' course.id %}" style="color: rgb(24, 113, 196);"><i
                                    class="fa fa-eye"></i></a>
                            {% if perms.academy.change_coursemodel%}
                            <a href="{% url 'updatecourse' course.id %}"><i class="fa fa-edit"
                                    style="color: rgb(24, 113, 196);"></i></a>
                            {% endif %}
                            {% if perms.academy.delete_coursemodel%}
                            <a href="{% url 'deletecourse' course.id %}"><i class="fa fa-trash"
                                    style="color: rgb(24, 113, 196);"></i></a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </center>
</body>

</html>

templates/deletestudent.html
<!-- <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <center>
      <h2>Delete Student</h2>
      <p>Are you sure you want to delete {{ student.full_name }}?</p>

      <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, Delete</button>
        <a href="{% url 'students' %}">Cancel</a>
      </form>
    </center>
  </body>
</html> -->

templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TechLearn Academy</title>
  </head>
  <body>
    <ul style="list-style: none;display: flex;">
        <li style="margin-left: 15px;"><a href="{% url 'courses' %}">View Courses</a> |</li>
        <li style="margin-left: 15px;"><a href="{% url 'trainers' %}">View Trainers</a> |</li>
        <li style="margin-left: 15px;"><a href="{% url 'students' %}"> View Students</a> |</li>
        {% if not user.is_authenticated %}
        <li style="margin-left: 15px;"><a href="{% url 'register' %}"> Register</a> |</li>
        <li style="margin-left: 15px;"><a href="{% url 'login' %}"> Login</a></li>
        {% endif %}
        {% if user.is_authenticated %}
        <li style="margin-left: 15px;"><a href="{% url 'logout' %}"> Logout</a></li>
        {% endif %}
    </ul>
    <center>
      <h1>Welcome to Our TechLearn Academy</h1>
      <h2>Total Available Courses: {{total_courses}}</h2>
      <h2>Total Available Trainers: {{total_trainers}}</h2>
      <h2>Total Students Currently Studying: {{total_students}}</h2>
    </center>
  </body>
</html>

templates/login.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
    <a href="{% url 'home' %} " style="margin-left: 200px;">Home</a>
    <h1 style="text-align: center;">Login Page</h1>
    <br>
    <form action="{% url 'login' %}" method="post" style="width: 500px;text-align: left;margin: auto;">
        {% csrf_token %}
        {{form | crispy}}
        <button type="submit" >Login</button>
    </form>
</body>
</html>

templates/register.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
    <h1 style="text-align: center;">Registration Page</h1>
    <br>
    <form action="{% url 'register' %}" method="post" style="width: 500px;text-align: left;margin: auto;">
        {% csrf_token %}
        {{form | crispy}}
        <button type="submit" >Submit</button>
    </form>
</body>
</html>

templates/studentdetails.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
  <body>
    <center>
    <h1>Student Detail Page - {{student.full_name}}</h1>
    <br>
    <p>Name:{{student.full_name}}</p>
    <p>Email:{{student.email}}</p>
    <p>Course Enrolled:{{student.enrolled_course}}</p>
    <p>Trainer:{{student.trainer}}</p>
    </center>
  </body>
</html>

templates/students.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Students</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
  </head>
  <body>
    <center>
      <ul style="list-style: none; ">
        <li >
          <a href="{% url 'home' %}">Back to Home</a>
        </li>
        {% if perms.academy.add_studentmodel %}
        <li style="margin-top: 10px;">
          <a href="{% url 'addstudent' %}">Add Student</a>
        </li>
        {% endif %}
      </ul>

      <h1>Total Available Students</h1>
      <br />
      <table border="1">
        <thead>
          <tr>
            <th>ID</th>
            <th>NAME</th>
            <th>EMAIL</th>
            <th>ENROLLED COURSE</th>
            <th>TRAINER</th>
            <th>ACTIVE OR NOT</th>
            {% if perms.academy.view_studentmodel%}<th>ACTION</th>{% endif %}
          </tr>
        </thead>

        <tbody>
          {% for student in students%}
          <tr>
            <td>{{student.id}}</td>
            <td>{{student.full_name}}</td>
            <td>{{student.email}}</td>
            <td>{{student.enrolled_course}}</td>
            <td>{{student.trainer}}</td>
            <td>{% if student.is_active %} Yes {% else %} No {% endif %}</td>
            {% if perms.academy.view_studentmodel%}
            <td>
              <div >
                <a href="{% url 'studentdetails' student.id %} " style="color: rgb(24, 113, 196);"><i class="fa fa-eye"></i></a>
                {% if perms.academy.change_studentmodel%}
                <a href="{% url 'updatestudent' student.id %}" style="color: rgb(24, 113, 196);"><i class="fa fa-edit"></i></a>
                {% endif %}
                {% if perms.academy.delete_studentmodel%}
                <a href="{% url 'deletestudent' student.id %}" style="color: rgb(24, 113, 196);"><i class="fa fa-trash"></i></a>
                {% endif %}
              </div>
            </td>
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </center>
  </body>
</html>

templates/trainerdetails.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
  <body>
    <center>
    <h1>Trainer Detail Page - {{trainer.full_name}}</h1>
    <br>
    <img src="{{trainer.trainer_photo.url}}" alt="{{trainer.full_name}} Image" style="width: 200px;height: 200px;">
    <p>Name:{{trainer.full_name}}</p>
    <p>Email:{{trainer.email}}</p>
    <p>Expertise:{{trainer.expertise}}</p>
    </center>
  </body>
</html>

templates/updatecourse.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
    <h1 style="text-align: center;">Update Course Page - {{course.course_name}}</h1>
    <br>
    <form  method="post" enctype="multipart/form-data" style="width: 500px;text-align:left;margin: auto;">
        {% csrf_token %}
        {{form | crispy}}
        <button type="submit">Update</button>
    </form>
</body>
</html>

templates/updatestudent.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
    <h1 style="text-align: center;">Update Student Page - {{student.full_name}}</h1>
    <br>
    <form method="post" style="width: 500px;text-align: left;margin: auto;">
        {% csrf_token %}
        {{form | crispy}}
        <button type="submit" >Update</button>
    </form>
</body>
</html>